### ISSUE TITLE
模型能否导出来onnx格式？

### ISSUE THREAD

**Issue by Kaze816** [FuNz-0/PromptAD#12]
我尝试在 test_reg.py中断点，将模型导出为onnx，发现有以下报错：

**torch.onnx.export(model, data, "test.onnx")**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "f:\pyenv\Torch118gpu\lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "f:\pyenv\Torch118gpu\lib\site-packages\torch\onnx\utils.py", line 1612, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "f:\pyenv\Torch118gpu\lib\site-packages\torch\onnx\utils.py", line 1134, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "f:\pyenv\Torch118gpu\lib\site-packages\torch\onnx\utils.py", line 1010, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "f:\pyenv\Torch118gpu\lib\site-packages\torch\onnx\utils.py", line 926, in _trace_and_get_graph_from_model
    raise RuntimeError(
RuntimeError: state_dict changed after running the tracer; something weird is happening in your model!

请问是什么原因呀？ 如何解决呢？

感谢你们的开源和回复！

**Comment by hccv** [comment]
我也遇到同样问题，请问有解决方案吗

**Comment by FuNz-0** [comment]
不好意思，我们没有尝试过导出onnx格式，所以没有遇到过类似的bug，我建议不要把整个模型直接进行导出，先把memory bank，学习到的prompt feature转换为模型参数，然后连同CLIP的视觉网络和语言网络一同导出试试。


***@***.***
 
发件人： hc
发送时间： 2024-08-23 16:50
收件人： FuNz-0/PromptAD
抄送： Subscribed
主题： Re: [FuNz-0/PromptAD] 模型能否导出来onnx格式？ (Issue #12)
我也遇到同样问题，请问有解决方案吗

**Comment by hccv** [comment]
> 不好意思，我们没有尝试过导出onnx格式，所以没有遇到过类似的bug，我建议不要把整个模型直接进行导出，先把memory bank，学习到的prompt feature转换为模型参数，然后连同CLIP的视觉网络和语言网络一同导出试试。 ***@***.*** 发件人： hc 发送时间： 2024-08-23 16:50 收件人： FuNz-0/PromptAD 抄送： Subscribed 主题： Re: [FuNz-0/PromptAD] 模型能否导出来onnx格式？ (Issue #12) 我也遇到同样问题，请问有解决方案吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的  感谢回复
