### ISSUE TITLE
Runtiming Bug

### ISSUE THREAD

**Issue by liumufenghua** [FuNz-0/PromptAD#25]
Traceback (most recent call last):
  File "C:\Users\liumufenghua\PromptAD\train_cls.py", line 257, in <module>
    main(args)
  File "C:\Users\liumufenghua\PromptAD\train_cls.py", line 189, in main
    metrics = fit(model, args, test_dataloader, device, check_path=check_path, train_data=train_dataloader)
  File "C:\Users\liumufenghua\PromptAD\train_cls.py", line 43, in fit
    for (data, mask, label, name, img_type) in train_data:
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\collate.py", line 173, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\collate.py", line 173, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\collate.py", line 222, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\_utils\collate.py", line 222, in <listcomp>
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
RuntimeError: Could not infer dtype of numpy.uint8 请问，这是什么原因？

**Comment by FuNz-0** [comment]
numpy 的版本问题




***@***.***
 
From: liumufenghua
Date: 2024-12-22 21:05
To: FuNz-0/PromptAD
CC: Subscribed
Subject: [FuNz-0/PromptAD] Runtiming Bug (Issue #25)
Traceback (most recent call last):
File "C:\Users\liumufenghua\PromptAD\train_cls.py", line 257, in 
main(args)
File "C:\Users\liumufenghua\PromptAD\train_cls.py", line 189, in main
metrics = fit(model, args, test_dataloader, device, check_path=check_path, train_data=train_dataloader)
File "C:\Users\liumufenghua\PromptAD\train_cls.py", line 43, in fit
for (data, mask, label, name, img_type) in train_data:
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\dataloader.py", line 631, in next
data = self._next_data()
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
data = self._dataset_fetcher.fetch(index) # may raise StopIteration
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 54, in fetch
return self.collate_fn(data)
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\collate.py", line 316, in default_collate
return collate(batch, collate_fn_map=default_collate_fn_map)
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\collate.py", line 173, in collate
return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed] # Backwards compatibility.
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\collate.py", line 173, in 
return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed] # Backwards compatibility.
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\collate.py", line 141, in collate
return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\collate.py", line 222, in collate_numpy_array_fn
return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
File "D:\Anaconda3\anaconda\envs\test_env\lib\site-packages\torch\utils\data_utils\collate.py", line 222, in 
return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
RuntimeError: Could not infer dtype of numpy.uint8 请问，这是什么原因？

**Comment by liumufenghua** [comment]
可以了，非常感谢！ 我还想请教您一个问题，现实中可以有大量ok的图像，请问您验证过full-shot的性能吗？在full-shot中能超过patchcore吗？如果使用自己的数据集promptAD的性能不好，优先调哪些参数呢？

**Comment by FuNz-0** [comment]
我们没有尝试过full shot，如果你们想调试超参数，可以试试提示工程，设计一些异常后缀可能对性能有改善
***@***.***
 
From: liumufenghua
Date: 2024-12-25 14:00
To: FuNz-0/PromptAD
CC: FuNz; Comment
Subject: Re: [FuNz-0/PromptAD] Runtiming Bug (Issue #25)
可以了，非常感谢！ 我还想请教您一个问题，现实中可以有大量ok的图像，请问您验证过full-shot的性能吗？在full-shot中能超过patchcore吗？如果使用自己的数据集promptAD的性能不好，优先调哪些参数呢？

**Comment by liumufenghua** [comment]
非常感谢您的回复，后续我会测试一下，祝好。
