### ISSUE TITLE
Execution error with run_cls.py

### ISSUE THREAD

**Issue by CaesarDingg** [FuNz-0/PromptAD#9]
I executed the run_cls.py file according to the readme and encountered the following error (my env: win10 with rtx3060):
`Traceback (most recent call last):
  File "C:\Users\35314\Desktop\PromptAD\PromptAD\CLIPAD\model.py", line 236, in encode_text_embeddings
    x = x + self.positional_embedding.to(cast_dtype)
RuntimeError: The size of tensor a (105) must match the size of tensor b (77) at non-singleton dimension 1`

可能是显卡不支持？

**Comment by FuNz-0** [comment]
你是不是修改了backbone&nbsp;







------------------ Original ------------------
From: CaesarDingg ***@***.***&gt;
Date: Tue,Jun 11,2024 11:29 AM
To: FuNz-0/PromptAD ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [FuNz-0/PromptAD] Execution error with run_cls.py (Issue #9)





 
I executed the run_cls.py file according to the readme and encountered the following error (my env: win10 with rtx3060):
 Traceback (most recent call last): File "C:\Users\35314\Desktop\PromptAD\PromptAD\CLIPAD\model.py", line 236, in encode_text_embeddings x = x + self.positional_embedding.to(cast_dtype) RuntimeError: The size of tensor a (105) must match the size of tensor b (77) at non-singleton dimension 1
 
可能是显卡不支持？

**Comment by CaesarDingg** [comment]
> 你是不是修改了backbone&nbsp;
> […](#)
> ------------------ Original ------------------ From: CaesarDingg ***@***.***&gt; Date: Tue,Jun 11,2024 11:29 AM To: FuNz-0/PromptAD ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [FuNz-0/PromptAD] Execution error with run_cls.py (Issue #9) I executed the run_cls.py file according to the readme and encountered the following error (my env: win10 with rtx3060): Traceback (most recent call last): File "C:\Users\35314\Desktop\PromptAD\PromptAD\CLIPAD\model.py", line 236, in encode_text_embeddings x = x + self.positional_embedding.to(cast_dtype) RuntimeError: The size of tensor a (105) must match the size of tensor b (77) at non-singleton dimension 1 可能是显卡不支持？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

没改，只尝试跑了visa

**Comment by FuNz-0** [comment]
77的尺度应该是正常的你debug跟踪一下x看看是哪里的问题; 



***@***.***
 
From: CaesarDingg
Date: 2024-06-11 11:34
To: FuNz-0/PromptAD
CC: FuNz; Comment
Subject: Re: [FuNz-0/PromptAD] Execution error with run_cls.py (Issue #9)
你是不是修改了backbone 
…
------------------ Original ------------------ From: CaesarDingg @.> Date: Tue,Jun 11,2024 11:29 AM To: FuNz-0/PromptAD @.> Cc: Subscribed @.> Subject: Re: [FuNz-0/PromptAD] Execution error with run_cls.py (Issue #9) I executed the run_cls.py file according to the readme and encountered the following error (my env: win10 with rtx3060): Traceback (most recent call last): File "C:\Users\35314\Desktop\PromptAD\PromptAD\CLIPAD\model.py", line 236, in encode_text_embeddings x = x + self.positional_embedding.to(cast_dtype) RuntimeError: The size of tensor a (105) must match the size of tensor b (77) at non-singleton dimension 1 可能是显卡不支持？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
没改，只尝试跑了visa

**Comment by WangFengJiee** [comment]
![Prompt](https://github.com/FuNz-0/PromptAD/assets/56255991/93c6cb2b-5f24-421a-8bfc-a211db550f7d)
具体是这个Prompt是105

**Comment by FuNz-0** [comment]
> ![Prompt](https://private-user-images.githubusercontent.com/56255991/338569041-93c6cb2b-5f24-421a-8bfc-a211db550f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTI1NzQsIm5iZiI6MTcxODExMjI3NCwicGF0aCI6Ii81NjI1NTk5MS8zMzg1NjkwNDEtOTNjNmNiMmItNWYyNC00MjFhLThiZmMtYTIxMWRiNTUwZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOGQyY2RkMDE5YjNmZWY1MzA0NDk4YjUxNmY2MGI4MDRmMjczYTNjNDBkODg3YmMwZDNlNTM4M2YwNGEyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.901N3Zzuh4Oxzwrd-6By5ixOKyHNAfQsF1O5k7Qa9iQ) 具体是这个Prompt是105

![image](https://github.com/FuNz-0/PromptAD/assets/45970865/a827dc74-f2c6-497f-914b-64a2275756d4)
这是我这边debug的结果，你看看你的问题在哪里

**Comment by WangFengJiee** [comment]
> > ![Prompt](https://private-user-images.githubusercontent.com/56255991/338569041-93c6cb2b-5f24-421a-8bfc-a211db550f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTI1NzQsIm5iZiI6MTcxODExMjI3NCwicGF0aCI6Ii81NjI1NTk5MS8zMzg1NjkwNDEtOTNjNmNiMmItNWYyNC00MjFhLThiZmMtYTIxMWRiNTUwZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOGQyY2RkMDE5YjNmZWY1MzA0NDk4YjUxNmY2MGI4MDRmMjczYTNjNDBkODg3YmMwZDNlNTM4M2YwNGEyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.901N3Zzuh4Oxzwrd-6By5ixOKyHNAfQsF1O5k7Qa9iQ) 具体是这个Prompt是105
> 
> ![image](https://private-user-images.githubusercontent.com/45970865/338601091-a827dc74-f2c6-497f-914b-64a2275756d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTM4OTcsIm5iZiI6MTcxODExMzU5NywicGF0aCI6Ii80NTk3MDg2NS8zMzg2MDEwOTEtYTgyN2RjNzQtZjJjNi00OTdmLTkxNGItNjRhMjI3NTc1NmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZGQ5Yzc0ODYxNzQ3YTYzYmY5ODFiOWFjMGQzM2ZhMDM4MTk1OTg3NmE1ZGQyYWI1M2FmOGE5OWE4ZGNiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.--4Y1au1gV0xT6UuB57woPrgv75Yba6tdCxlA-IW3j8) 这是我这边debug的结果，你看看你的问题在哪里

![image](https://github.com/FuNz-0/PromptAD/assets/56255991/641b1508-52b5-4e90-b4b6-078307a4a107)
#
问题貌似出在这里，源代码默认的是100，应该是1吧

**Comment by CaesarDingg** [comment]
> > > ![Prompt](https://private-user-images.githubusercontent.com/56255991/338569041-93c6cb2b-5f24-421a-8bfc-a211db550f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTI1NzQsIm5iZiI6MTcxODExMjI3NCwicGF0aCI6Ii81NjI1NTk5MS8zMzg1NjkwNDEtOTNjNmNiMmItNWYyNC00MjFhLThiZmMtYTIxMWRiNTUwZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOGQyY2RkMDE5YjNmZWY1MzA0NDk4YjUxNmY2MGI4MDRmMjczYTNjNDBkODg3YmMwZDNlNTM4M2YwNGEyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.901N3Zzuh4Oxzwrd-6By5ixOKyHNAfQsF1O5k7Qa9iQ) 具体是这个Prompt是105
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/45970865/338601091-a827dc74-f2c6-497f-914b-64a2275756d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTM4OTcsIm5iZiI6MTcxODExMzU5NywicGF0aCI6Ii80NTk3MDg2NS8zMzg2MDEwOTEtYTgyN2RjNzQtZjJjNi00OTdmLTkxNGItNjRhMjI3NTc1NmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZGQ5Yzc0ODYxNzQ3YTYzYmY5ODFiOWFjMGQzM2ZhMDM4MTk1OTg3NmE1ZGQyYWI1M2FmOGE5OWE4ZGNiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.--4Y1au1gV0xT6UuB57woPrgv75Yba6tdCxlA-IW3j8) 这是我这边debug的结果，你看看你的问题在哪里
> 
> ![image](https://private-user-images.githubusercontent.com/56255991/338608778-641b1508-52b5-4e90-b4b6-078307a4a107.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTY0NTgsIm5iZiI6MTcxODExNjE1OCwicGF0aCI6Ii81NjI1NTk5MS8zMzg2MDg3NzgtNjQxYjE1MDgtNTJiNS00ZTkwLWI0YjYtMDc4MzA3YTRhMTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YWRmNDkwZDAzMWJiOTFmMmE3YjQ2ZGE4ZGE0MmVmNGUzODE5NmQyYjEyZmRhNzBiZjQwOWMyZGZiMzUwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vqqih5RVqnHBzTFXy0WyeleZNAUCkTamdVXNBiEr7nI)
> 
> 问题貌似出在这里，源代码默认的是100，应该是1吧

跑通了，谢谢！

**Comment by AlirezaSalehy** [comment]
> 这里

And by changing the n_ctx_ab to 1 can you just reproduce the reported results on ViSA?
